package org.mastodon.mamut.appose;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import org.apposed.appose.Appose;
import org.junit.jupiter.api.Test;

class ApposePixiTest
{
	static final String ENV_CONTENT = "[workspace]\n"
			+ "name = 'stardist-test'\n"
			+ "version = '0.0.1'\n"
			+ "description = 'Mastodon spot detector using StarDist3D.'\n"
			+ "authors = ['Curtis Rueden', 'Carlos Garcia', 'Jean-Yves Tinevez', 'Stefan Hahmann']\n"
			+ "channels = ['conda-forge']\n"
			+ "platforms = ['osx-arm64', 'osx-64', 'linux-64', 'win-64']\n"
			+ "\n"
			+ "[dependencies]\n"
			+ "python = '==3.10'\n"
			+ "numpy = '<2'\n"
			+ "scipy = '*'\n"
			+ "pip = '*'\n"
			+ "\n"
			+ "[pypi-dependencies]\n"
			+ "appose = '==0.7.2'\n"
			+ "stardist = '==0.9.1'\n"
			+ "csbdeep = '*'\n"
			+ "ndv = { extras = ['qt'] }\n"
			+ "pygfx = '<0.13.0'\n"
			+ "\n"
			+ "[target.osx-64.dependencies]\n"
			+ "python = '*'\n"
			+ "\n"
			+ "[target.osx-arm64.dependencies]\n"
			+ "python = '*'\n"
			+ "\n"
			+ "# PyPI deps common per-OS:\n"
			+ "[target.win-64.pypi-dependencies]\n"
			+ "tensorflow = '==2.10.1'\n"
			+ "\n"
			+ "[target.linux-64.pypi-dependencies]\n"
			+ "tensorflow = '==2.10.1'\n"
			+ "\n"
			+ "[target.osx-64.pypi-dependencies]\n"
			+ "tensorflow = '*'                 # latest CPU TF for Intel mac\n"
			+ "\n"
			+ "[target.osx-arm64.pypi-dependencies]\n"
			+ "tensorflow-macos = '*'           # latest TF for Apple Silicon\n"
			+ "tensorflow-metal = '*'           # Metal plugin\n"
			+ "\n"
			+ "# ---------------- Macos no metal - ONLY APPLE SILICON ----------------\n"
			+ "[feature.nometal]\n"
			+ "channels = ['conda-forge']\n"
			+ "\n"
			+ "[feature.nometal.target.osx-arm64.pypi-dependencies]\n"
			+ "tensorflow = '*'\n"
			+ "\n"
			+ "# ---------------- CUDA feature (Windows/Linux only) ----------------\n"
			+ "[feature.cuda]\n"
			+ "channels = ['nvidia', 'conda-forge']   # optional; inherits from workspace\n"
			+ "\n"
			+ "[feature.cuda.target.win-64.dependencies]\n"
			+ "cudatoolkit = '11.2.*'\n"
			+ "cudnn = '8.1.*'\n"
			+ "\n"
			+ "[feature.cuda.target.linux-64.dependencies]\n"
			+ "cudatoolkit = '11.2.*'\n"
			+ "cudnn = '8.1.*'\n"
			+ "\n"
			+ "# Activation only when the 'cuda' feature is part of the active environment:\n"
			+ "[feature.cuda.target.win-64.activation.env]\n"
			+ "PATH = '%CONDA_PREFIX%\\\\\\\\Library\\\\\\\\bin;%PATH%'\n"
			+ "\n"
			+ "[feature.cuda.target.linux-64.activation.env]\n"
			+ "LD_LIBRARY_PATH = '$CONDA_PREFIX/lib:${LD_LIBRARY_PATH:-}'\n"
			+ "\n"
			+ "# Dev feature\n"
			+ "[feature.dev.dependencies]\n"
			+ "pytest = '*'\n"
			+ "ruff = '*'\n"
			+ "\n"
			+ "[feature.dev.pypi-dependencies]\n"
			+ "build = '*'\n"
			+ "validate-pyproject = { extras = ['all'] }\n"
			+ "\n"
			+ "# ---------------- TASKS (cmd holds the whole command line) ---------------- #\n"
			+ "[tasks]\n"
			+ "# Main application\n"
			+ "start = 'python src/main.py'\n"
			+ "\n"
			+ "# Development tasks\n"
			+ "lint = 'ruff check --fix && ruff format'\n"
			+ "test = 'pytest -v -p no:faulthandler tests'\n"
			+ "validate = 'validate-pyproject pyproject.toml'\n"
			+ "dist = 'python -m build'\n"
			+ "\n"
			+ "# Combined tasks\n"
			+ "check = { depends-on = ['validate', 'lint'] }\n"
			+ "\n"
			+ "# ---------------- ENVIRONMENTS ---------------- #\n"
			+ "\n"
			+ "[environments]\n"
			+ "default = { solve-group = 'default' }\n"
			+ "cuda = { features = ['cuda'], solve-group = 'default' }\n"
			+ "nometal = { features = ['nometal'], solve-group = 'default' }\n"
			+ "dev = { features = ['dev'], solve-group = 'default' }\n"
			+ "cuda-dev = { features = ['cuda', 'dev'], solve-group = 'default' }";

	@Test
	void testApposePixi()
	{
		assertDoesNotThrow( () -> Appose.pixi().content( ENV_CONTENT ).build() );
	}
}
